package com.example.myapplication.profile.model

import com.google.errorprone.annotations.Keep

@Keep
data class Profile(
    val address: Address,
    val badReviewCount: Int,
    val bodyShapeId: String,
    val brandCode: String,
    val brandId: Int,
    val brandName: String,
    val dob: String,
    val emailPc: String,
    val favouriteCount: Int,
    val firstName: String,
    val firstNameKana: String,
    val followerCount: Int,
    val followingCount: Int,
    val genderId: String,
    val goodReviewCount: Int,
    val heightId: String,
    val id: Int,
    val image: Image,
    val interests: List<Interest>,
    val isDeleted: Boolean,
    val isProfileVerified: Boolean,
    val isStripeRegistered: Boolean,
    val lastName: String,
    val lastNameKana: String,
    val memberId: String,
    val nickname: String,
    val orderCompletedPostCount: Int,
    val orderPlacedPostCount: Int,
    val permission: Permission,
    val personalColorId: String,
    val postCount: Int,
    val publishedPostCount: Int,
    val shoeSizeId: String,
    val shoulderStatureId: String,
    val snsDetails: SnsDetails,
    val specificStylingId1: String,
    val specificStylingId2: String,
    val specificStylingId3: String,
    val status: String,
    val stripeRegStatus: String,
    val totalReviewCount: Int,
    val weightId: String
)